server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        # ── Clientes ──────────────────────────────────────
        - id: clientes-service
          uri: lb://clientes-service
          predicates:
            - Path=/api/v1/clientes/**

        # ── Usuarios ──────────────────────────────────────
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/v1/usuarios/**

        # ── Productos ─────────────────────────────────────
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/v1/productos/**

        # ── Búsqueda ──────────────────────────────────────
        - id: busqueda-service
          uri: lb://busqueda-service
          predicates:
            - Path=/api/v1/busqueda/**

        # ── Reembolsos ────────────────────────────────────
        - id: reembolsos-service
          uri: lb://reembolsos-service
          predicates:
            - Path=/api/v1/reembolsos/**

        # ── Notificaciones ────────────────────────────────
        - id: notificaciones-service
          uri: lb://notificaciones-service
          predicates:
            - Path=/api/v1/notificaciones/**
