eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Login
          uri: lb://login_bd
          predicates:
            - Path=/api/v1/**

        - id: Usuario
          uri: lb://usuarios_bd
          predicates:
            - Path=/api/v1/usuarios/**

        - id: Producto
          uri: lb://producto_bd
          predicates:
            - Path=/api/v1/productos/**

        - id: dbCompra
          uri: lb://ms_compras
          predicates:
            - Path=/api/v1/compras/**

        - id: dbResenas
          uri: lb://ms_resenas
          predicates:
            - Path=/api/v1/resenas/**

        - id: dbEnvio
          uri: lb://ms_envios
          predicates:
            - Path=/api/v1/envios/**

        - id: Reembolsos
          uri: lb://reembolsos_db
          predicates:
            - Path=/api/v1/reembolsos/**

        - id: Notificaciones
          uri: lb://notificaciones_db
          predicates:
            - Path=/api/v1/notificaciones/**

        - id: dbReportes
          uri: lb://ms_reportes
          predicates:
            - Path=/api/v1/reportes/**

        - id: Remuneraciones
          uri: lb://remuneraciones_db
          predicates:
            - Path=/api/v1/remuneraciones/**